use std::path::PathBuf;

use clap::Command;

use crate::{qc::results::Results, utils::commands::add_verbosity_args};

use super::{cohort, sample};

//===============//
// Command setup //
//===============//

pub fn get_command() -> Command {
    Command::new("plot")
        .about("Produces plots for data generated by `ngs qc`.")
        .subcommand_required(true)
        .subcommand(add_verbosity_args(cohort::get_command()))
        .subcommand(add_verbosity_args(sample::get_command()))
}

pub struct FilepathResults<'a>(pub &'a PathBuf, pub Results);

//===================//
// Sample Plot trait //
//===================//

pub trait SamplePlot {
    fn name(&self) -> &'static str;
    fn filename(&self) -> &'static str;
    fn generate(&self, filepath_results: &FilepathResults<'_>) -> anyhow::Result<plotly::Plot>;
}

//===================//
// Cohort Plot trait //
//===================//

pub trait CohortPlot {
    fn name(&self) -> &'static str;
    fn filename(&self) -> &'static str;
    fn generate(&self, filepath_results: &[FilepathResults<'_>]) -> anyhow::Result<plotly::Plot>;
}

//================================//
// Get all supported sample plots //
//================================//

pub fn get_all_sample_plots() -> Vec<Box<dyn SamplePlot>> {
    vec![
        Box::new(sample::quality_score_distribution::QualityScoreDistributionPlot),
        Box::new(sample::gc_content_distribution::GCContentDistributionPlot),
    ]
}

//================================//
// Get all supported cohort plots //
//================================//

pub fn get_all_cohort_plots() -> Vec<Box<dyn CohortPlot>> {
    vec![Box::new(
        cohort::gc_content_distribution::GCContentDistributionPlot,
    )]
}
